// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_high_score = "CgkIhKi4kekCEAIQAA"; // <GPGSID>
        public const string achievement_5th_cat_open = "CgkIhKi4kekCEAIQAg"; // <GPGSID>
        public const string achievement_10th_cat_open = "CgkIhKi4kekCEAIQAw"; // <GPGSID>
        public const string achievement_access_for_more_than_7_days = "CgkIhKi4kekCEAIQBA"; // <GPGSID>
        public const string achievement_open_game = "CgkIhKi4kekCEAIQAQ"; // <GPGSID>
        public const string achievement_summon_more_than_1000_cats = "CgkIhKi4kekCEAIQBQ"; // <GPGSID>

}

